---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: publish_emby
    image: plugins/docker:latest
    settings:
      auto_tag: true
      auto_tag_suffix: latest
      dockerfile: emby_crack/Dockerfile
      repo: faintghost/emby_happy
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    when:
      event:
        - push
