name: build-and-publish-latest
on: [push]
jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch
    steps:
      - uses: actions/checkout@v2 # Checking out the repo
      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.BUILD_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: aria2-ariang-ui # Provide only Docker image name, tag will be automatically set to latest
          dockerfile: aria2/Dockerfile
